---
name: Deploy to AWS

on:
  workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Deployment
    env:
      AWS_GITHUB_PROVIDER_ARN: ${{ secrets.AWS_GITHUB_PROVIDER_ARN }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          npm install -g aws-cdk
          pip3 install -r requirements.txt
          pip3 install -r requirements-dev.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: GithubRunnerDeployment
      - name: Bootstrap environment
        run: cdk bootstrap
      - name: Synthesize stack
        run: cdk synth AptlyRepositoryStack
      - name: Deploy stack
        run: cdk deploy --require-approval never AptlyRepositoryStack --outputs-file /tmp/cdk-outputs.json
      - name: Export CDK outputs
        id: cdk
        run: |
          echo "AWS_APTLY_BUCKET_NAME=$(cat /tmp/cdk-outputs.json | jq -r .AptlyRepositoryStack.BucketName)" >> $GITHUB_OUTPUT
          echo "AWS_APTLY_PUBLISHER_ROLE_ARN=$(cat /tmp/cdk-outputs.json | jq -r .AptlyRepositoryStack.PublisherRoleArn)" >> $GITHUB_OUTPUT
          echo "AWS_APTLY_KEY_MANAGER_ROLE_ARN=$(cat /tmp/cdk-outputs.json | jq -r .AptlyRepositoryStack.KeyManagerRoleArn)" >> $GITHUB_OUTPUT
      - name: Update bucket secret (KeyRotation)
        run: >
          invoke create-github-secret
          --repo ${{ github.repository_id }}
          --environment KeyRotation
          --token ${{ secrets.REPOSITORY_PAT }}
          --name AWS_APTLY_BUCKET_NAME
          --value ${{ steps.cdk.outputs.AWS_APTLY_BUCKET_NAME }}
      - name: Update key manager role secret
        run: >
          invoke create-github-secret
          --repo ${{ github.repository_id }}
          --environment KeyRotation
          --token ${{ secrets.REPOSITORY_PAT }}
          --name AWS_APTLY_KEY_MANAGER_ROLE_ARN
          --value ${{ steps.cdk.outputs.AWS_APTLY_KEY_MANAGER_ROLE_ARN }}
      - name: Update bucket secret (Publish)
        run: >
          invoke create-github-secret
          --repo ${{ github.repository_id }}
          --environment Publish
          --token ${{ secrets.REPOSITORY_PAT }}
          --name AWS_APTLY_BUCKET_NAME
          --value ${{ steps.cdk.outputs.AWS_APTLY_BUCKET_NAME }}
      - name: Update publisher role secret
        run: >
          invoke create-github-secret
          --repo ${{ github.repository_id }}
          --environment Publish
          --token ${{ secrets.REPOSITORY_PAT }}
          --name AWS_APTLY_PUBLISHER_ROLE_ARN
          --value ${{ steps.cdk.outputs.AWS_APTLY_PUBLISHER_ROLE_ARN }}
      
