---
name: Deploy to AWS

on:
  workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Deployment
    env:
      AWS_GITHUB_PROVIDER_ARN: ${{ secrets.AWS_GITHUB_PROVIDER_ARN }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          npm install -g aws-cdk
          pip3 install -r requirements.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: GithubRunnerDeployment
      - name: Bootstrap environment
        run: cdk bootstrap
      - name: Synthesize stack
        run: cdk synth AptlyS3PocStack
      - name: Deploy stack
        run: |
          cdk deploy --require-approval never AptlyS3PocStack --output-file ./cdk-outputs.json
          ls
          ls cdk.out
      - name: Get CDK outputs
        id: cdk-outputs
        run: |
          ls
          ls cdk.out
          cat ./cdk-outputs.json
          echo "AWS_APTLY_REPOSITORY=$(cat cdk-outputs.json | jq -r .AptlyRepositoryBucketName)" >> $GITHUB_OUTPUT
          echo "AWS_APTLY_PUBLISH_ROLE_ARN=$(cat cdk-outputs.json | jq -r .AptlyRepositoryPublisherRoleArn)" >> $GITHUB_OUTPUT
      - name: Update Aptly repository secret
        uses: gliech/create-github-secret-action@v1
        with:
          name: AWS_APTLY_REPOSITORY
          value: ${{ steps.cdk-outputs.outputs.AWS_APTLY_REPOSITORY }}
          pa_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update publish role secret
        uses: gliech/create-github-secret-action@v1
        with:
          name: AWS_APTLY_PUBLISH_ROLE_ARN
          value: ${{ steps.cdk-outputs.outputs.AWS_APTLY_PUBLISH_ROLE_ARN }}
          pa_token: ${{ secrets.GITHUB_TOKEN }}
