---
name: Deploy to AWS

on:
  workflow_dispatch

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Deployment
    env:
      AWS_GITHUB_PROVIDER_ARN: ${{ secrets.AWS_GITHUB_PROVIDER_ARN }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          npm install -g aws-cdk
          pip3 install -r requirements.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: GithubRunnerDeployment
      - name: Bootstrap environment
        run: cdk bootstrap
      - name: Synthesize stack
        run: cdk synth AptlyS3PocStack
      - name: Deploy stack
        run: cdk deploy --require-approval never AptlyS3PocStack --outputs-file /tmp/cdk-outputs.json
      - name: Export CDK outputs
        id: cdk
        run: |
          cat /tmp/cdk-outputs.json
          echo "AWS_APTLY_PACKAGE_BUCKET_NAME=$(cat /tmp/cdk-outputs.json | jq -r .AptlyS3PocStack.AptlyRepositoryPackageBucketName)" >> $GITHUB_OUTPUT
          echo "AWS_APTLY_KEY_BUCKET_NAME=$(cat /tmp/cdk-outputs.json | jq -r .AptlyS3PocStack.AptlyRepositoryKeyBucketName)" >> $GITHUB_OUTPUT
          echo "AWS_APTLY_PUBLISHER_ROLE_ARN=$(cat /tmp/cdk-outputs.json | jq -r .AptlyS3PocStack.AptlyRepositoryPublisherRoleArn)" >> $GITHUB_OUTPUT
          echo "AWS_APTLY_KEY_MANAGER_ROLE_ARN=$(cat /tmp/cdk-outputs.json | jq -r .AptlyS3PocStack.AptlyRepositoryKeyManagerRoleArn)" >> $GITHUB_OUTPUT
          echo $AWS_APTLY_KEY_MANAGER_ROLE_ARN
      - name: Update package bucket secret (Publish)
        uses: mmercan/actions-set-secret@v/4.0.0
        with:
          name: AWS_APTLY_PAKCAGE_BUCKET_NAME
          value: ${{ steps.cdk.outputs.AWS_APTLY_PACKAGE_BUCKET_NAME }}
          repository: TSNoble/aptly-s3-poc
          token: ${{ secrets.REPOSITORY_PAT }}
          environment: Publish
      - name: Update publisher role secret (Publish)
        uses: mmercan/actions-set-secret@v/4.0.0
        with:
          name: AWS_APTLY_PUBLISHER_ROLE_ARN
          value: ${{ steps.cdk.outputs.AWS_APTLY_PUBLISHER_ROLE_ARN }}
          repository: TSNoble/aptly-s3-poc
          token: ${{ secrets.REPOSITORY_PAT }}
          environment: Publish
      - name: Update key bucket secret (KeyRotation)
        uses: mmercan/actions-set-secret@v/4.0.0
        with:
          name: AWS_APTLY_KEY_BUCKET_NAME
          value: ${{ steps.cdk.outputs.AWS_APTLY_KEY_BUCKET_NAME }}
          repository: TSNoble/aptly-s3-poc
          token: ${{ secrets.REPOSITORY_PAT }}
          environment: KeyRotation
      - name: Update key manager role secret (KeyRotation)
        uses: mmercan/actions-set-secret@v/4.0.0
        with:
          name: AWS_APTLY_KEY_MANAGER_ROLE_ARN
          value: ${{ steps.cdk.outputs.AWS_APTLY_KEY_MANAGER_ROLE_ARN }}
          repository: TSNoble/aptly-s3-poc
          token: ${{ secrets.REPOSITORY_PAT }}
          environment: KeyRotation
