---
name: Publish Snapshot

on:
  workflow_dispatch:
    inputs:
      repository_name:
        required: true
        type: string
        default: "rivelin-source-dependencies"
        description: "The name of the Aptly repository."
      debian_path:
        required: true
        type: string
        default: "debs"
        description: "The path to the .deb packages."
      version:
        required: true
        type: string
        description: "The version of the snapshot."
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
        description: "The name of the Aptly repository."
      debian_path:
        required: true
        type: string
        description: "The path to the .deb packages."
      version:
        required: true
        type: string
        description: "The version of the snapshot."
jobs:
  publish_:
    runs-on: ubuntu-latest
    environment: Publish
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "deb http://repo.aptly.info/ squeeze main" | sudo dd of=/etc/apt/sources.list.d/aptly.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EE727D4449467F0E
          sudo apt-get update && sudo apt-get install -y aptly gpgv1 gnupg1
          pip3 install -r requirements-dev.txt
      - name: Generate Aptly config
        run: >
          jinja2 ./config/.aptly.conf.j2
          -D repository=${{ inputs.repository-name }}
          -D region=${{ secrets.AWS_DEFAULT_REGION }}
          -D bucket=${{ secrets.AWS_APTLY_BUCKET_NAME }}
          -o /tmp/.aptly.conf
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_APTLY_PUBLISHER_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: GithubRunnerAptlyPublishSnapshot
      - name: Import signing key
        run: |
          echo -n ${{ secrets.APTLY_GPG_PRIVATE_KEY }} | base64 --decode | gpg1 --import
      - name: Publish new Snapshot
        run: |
          aptly repo create -distribution=jammy -component=main -config=/tmp/.aptly.conf ${{ inputs.repository-name }}
          aptly repo add -config=/tmp/.aptly.conf ${{ inputs.repository-name }} rivelin-source-dependencies ${{ inputs.debian_path }}
          aptly snapshot create -config=/tmp/.aptly.conf ${{ inputs.repository-name}}-${{ inputs.version }} from repo rivelin-source-dependencies
          aptly -architectures=i386 publish snapshot -config=/tmp/.aptly.conf ${{ inputs.repository-name }}-${{ inputs.version }} s3:${{ inputs.repository-name }}-s3:.
