---
name: Test Infrastructure

on:
  workflow_call:
    inputs:
      aws-aptly-bucket-name:
        required: true
        type: string
        description: "The name of the S3 bucket hosting Aptly packages and the public key."
      aws-aptly-publisher-role-arn:
        required: true
        type: string
        description: "The ARN of the role allowed to publish Aptly packages to the S3 bucket."
      aws-aptly-key-manager-role-arn:
        required: true
        type: string
        description: "The ARN of the role allowed to write a new public key to the S3 bucket."

jobs:
  test-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r requirements-dev.txt
          echo Bucket=${{ inputs.aws-aptly-bucket-name }}
      - name: Run tests
        env:
          AWS_APTLY_BUCKET_NAME: ${{ inputs.aws-aptly-bucket-name }}
          AWS_APTLY_KEY_MANAGER_ROLE_ARN: ${{ inputs.aws-aptly-key-manager-role-arn }}
        run: pytest
